language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t aemarquez1993/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true aemarquez1993/react-test npm test

after_success:
    - docker build -t aemarquez1993/multi-client ./client
    - docker build -t aemarquez1993/multi-worker ./worker
    - docker build -t aemarquez1993/multi-nginx ./nginx
    - docker build -t aemarquez1993/multi-server ./server
    # Log in to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push aemarquez1993/multi-client
    - docker push aemarquez1993/multi-worker
    - docker push aemarquez1993/multi-nginx
    - docker push aemarquez1993/multi-server

deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'multi-docker'
    env: 'Multidocker-env-1'
    bucket_name: 'elasticbeanstalk-us-east-1-712233341720'
    bucket_path: 'docker-multi'
    on:
      branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
